# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoPong', '0002_auto_20180427_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='dojoPong.League'),
        ),
        migrations.AlterField(
            model_name='user',
            name='opponent_records',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='dojoPong.Record'),
        ),
    ]
