# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-27 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoPong', '0003_auto_20180427_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dojoPong.Record'),
        ),
    ]
