# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-19 23:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoPong', '0008_auto_20180619_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='scores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='dojoPong.Score'),
        ),
    ]
