# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojoPong', '0011_auto_20180620_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='location',
            field=models.CharField(default='Enter location or address info...', max_length=255),
        ),
    ]
