# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoPong', '0012_auto_20180620_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winnner_points', models.IntegerField()),
                ('loser_points', models.IntegerField()),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='dojoPong.League')),
                ('loser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defeat', to='dojoPong.Player')),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='win', to='dojoPong.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='record',
            name='scores',
        ),
        migrations.AddField(
            model_name='record',
            name='draws',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
