# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 23:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojoPong', '0014_auto_20180621_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defeat', to='dojoPong.Player'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='win', to='dojoPong.Player'),
        ),
    ]
